### ISSUE TITLE
image_recognition_msgs/GetPersons.h is not found

### ISSUE THREAD

**Issue by nnn112358** [tue-robotics/openpose_ros#1]
You have a wonderful work. I wanted to try your work but I could not performance.
I want you to follow me.

enviroment:
>Ubuntu 16.04+CUDA8.0+ROS pkg:kinetic

Executed command:
>catkin_make

Error
> fatal error: image_recognition_msgs/GetPersons.h:

Next,
I tried "sudo apt-get install ros-kinetic-image-recognition-msgs "
But It was not included here.

I think that it is necessary to include ”GetPersons.h” in ”openpose_ros”

**Comment by LoyVanBeek** [comment]
It seems https://github.com/tue-robotics/image_recognition/blob/master/image_recognition_msgs/srv/GetPersons.srv does provide the needed file. 
It should also be generated through https://github.com/tue-robotics/image_recognition/blob/master/image_recognition_msgs/CMakeLists.txt#L27 

The current release does not (yet) include GetPersons and it will need some work before it will be released.

**Comment by nnn112358** [comment]
Thank you for answering.
I corrected it according to your point, I was able to succeed catkin_make !
I'm expecting the next release.
