### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by nnn112358** [tue-robotics/openpose_ros#2]
Thank you for responding yesterday soon.
I have another question.I will be pleased if you follow me.

When I created and executed "openpose_ros" client node, "Segmentation fault" Error got up in openpose_ros_node.

enviroment:
 >Ubuntu 16.04+CUDA8.0+ROS pkg:kinetic

Executed command:
 >catkin_make
 >rosrun openpose_ros openpose_ros_node 
 >rosrun openpose_ros openpose_ros_client 
 >→"openpose_ros_client" is  what I made
 >　https://github.com/nnn112358/openpose_ros/blob/master/src/openpose_ros_client.cpp

Error
>$ rosrun openpose_ros openpose_ros_node 
>[ INFO] [1495355758.918419426]: detectPosesCallback
>[ INFO] [1495355758.918782543]: Perform forward pass with the following settings:
>[ INFO] [1495355758.918796075]: - net_input_size: [656 x 368]
>[ INFO] [1495355758.918823517]: - num_scales: 1
>[ INFO] [1495355758.918871126]: - scale_gap: 0.3
>[ INFO] [1495355758.918893902]: - image_size: [640 x 480]
>Segmentation fault 

Segmentation faul  is happening below
Below,"cv_mat_to_op_input.format(image)" seems to be the cause
>openpose_ros_node.cpp
>122: g_pose_extractor->forwardPass(cv_mat_to_op_input.format(image), image.size());

If you have a point to worry about, please let me know.
Original OpenPose is working properly.

And,Perhaps openpose is updated, so it may be an error. 
Will not you check with the latest Openpose?

**Comment by reinzor** [comment]
Thanks for showing interest in this package. This package however is very experimental and I experiences these linking problems/segfault also. If you are interested in using openpose with ROS, we have a fork that does this: https://github.com/tue-robotics/openpose

Again, this is highly experimental code and if we have the cycles, I would like to release this properly but I don';t have that much time right now. Thanks for trying and adding the issue though :)

**Comment by nnn112358** [comment]
Thank you for your reply. I understood that it is an experimental code.

OpenPose & ROS using Customize Makefile was also making me, I was interested in OpenPose using catkin.
Your source is using catkin, and it is sophisticated.
https://github.com/nnn112358/openpose/blob/master/examples/user_code/openpose_ros_1.cpp

Even with fork OpenPose Code, I got an Segmentation fault error in my environment.
I am going to look it up a bit.

Thanks.
